apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: secure-prod
type: Opaque
stringData:
  # Этот пароль будет зашифрован внутри кластера
  POSTGRES_PASSWORD: "super-secure-password-123" 
  POSTGRES_USER: "secure_app_user"
  POSTGRES_DB: "secure_app_db"