apiVersion: v1
kind: Namespace
metadata:
  name: secure-prod
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-network-policy
  namespace: secure-prod
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - ports:
    - protocol: TCP
      port: 8080
  egress: []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-frontend
  namespace: secure-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        checkov.io/skip1: CKV_K8S_15=Local Minikube requires Never pull policy
        checkov.io/skip2: CKV_K8S_43=Local dev does not use SHA256 digests
        checkov.io/skip3: CKV_K8S_35=Environment variables are acceptable for local demo
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx-container
        image: my-secure-frontend:v2
        imagePullPolicy: Never
        env:
        - name: MY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-super-secret
              key: ADMIN_PASSWORD
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "100m"
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /tmp
          name: tmp-volume
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: tmp-volume
        emptyDir: {}
