apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: secure-prod
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: secure-prod
# ... (здесь ваши apiVersion, kind и metadata) ...
spec:
  rules:
    - http:
        paths:
          # Маршрут для API (Бэкенд)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: {{ .Values.backend.service.port }}
          
          # Тестовый маршрут БД (Бэкенд)
          - path: /test-db
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.service.name }}
                port:
                  number: {{ .Values.backend.service.port }}
                  
          # Маршрут по умолчанию (Фронтенд)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service.name }}
                port:
                  number: {{ .Values.frontend.service.port }}